node {
  stage ('SCM Checkout' ) 

    git 'https://github.com/petercashparker/TestProject'
    // gte maven home path
  stage ('Compile-Package'){
    def mvnHome = tool 'tool name: '', type: 'maven'
    sh "${mvnHome}/bin/mvn package"
         }
}
