node {
  stage ('SCM Checkout' ) {
    
    git 'https://github.com/petercashparker/TestProject'
  }
  stage ('Compile-Package'){
    //Get maven home path
        def mvnHome = tool 'tool name: '', type: 'maven'

    sh "${mvnHome/bin/mvn}"
         }
}
