node {
  stage ('SCM Checkout' ) {
    
    git 'TestProject/GitTestProject/Jenkinsfile'
  }
  stage ('Compile-Package'){
    //Get maven home path
        def mvnHome = tool 'tool name: '', type: 'maven'

    sh "${mvnHome/bin/mvn}"
         }
}
