node {
  stage ('SCM Checkout' ) {
    tool 'tool name: '', type: 'maven'
    
    git 'https://github.com/petercashparker/TestProject'
  }
  stage ('Compile-Package'){
         sh 'mvn package'
         }
}
